LOG:
  LOG_DIR: log
  LOG_FILE_NAME: log.log
  LOG_OUTPUT_LEVEL: INFO
source_code_dir: H:/netdisk_backup/miluo/code/ocr/seal_and_top_hole_release
destination_code_dir: C:/Users/lr/Desktop/ocr


#source_code_dir: H:/torch_project/daokou/release/daokou_middleware
#destination_code_dir: C:/Users/lr/Desktop/daokou_midle