LOG:
  LOG_DIR: log
  LOG_FILE_NAME: log.log
  LOG_OUTPUT_LEVEL: INFO
#source_code_dir: H:/torch_project/daokou/release/container_and_car_num_release
#destination_code_dir: C:/Users/lr/Desktop/daok_reslease


source_code_dir: H:/torch_project/daokou/release/daokou_middleware
destination_code_dir: C:/Users/lr/Desktop/daokou_midle